### ISSUE TITLE
Unexpected duplicate resource generation.

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor-stream#3]
Associated test case:
https://gist.github.com/masterav10/9d7e3f5009d753fe74d3
Using: compile "io.projectreactor:reactor-fluxion:2.5.0.BUILD-SNAPSHOT"

I was experimenting with the latest streams, and found a strange issue which is I think is related to the way I'm nesting streams + filter(). The problem is that p3 generates two resources once the combineLatest requirements are met. The first resource is passed to cleanup pipeline (p4), and the second is passed to the recording pipeline (p5).

Replace p3 with this to see the duplicate objects being printed:
        `Fluxion<SomeResource> p3 = Fluxion.combineLatest(t -> {
            return Tuple.of((Boolean) t[0], t[1]);
        }, p1, p2).distinctUntilChanged(Tuple2::getT1).filter(Tuple2::getT1).doOnNext(System.err::println)
                .map(t -> new SomeResource()).doOnNext(t -> p3C.incrementAndGet());`

As it turns out, if you do not consume on p4 or p5, only one resource is generated. This indicates to me that the pipelines are completely unique, even though they use the same source (p3). And maybe that's the intention, although certainly not the behavior I was expecting.

As a workaround, I modified the resource generation part of p3 to use a cache. In my actual code, I simply mapped the resource to a key (p2 objects have a timestamp in my code). This ensures that the same resource sent down both paths. But there are number repercussions, such as thread safety and extra memory, etc.

**Comment by masterav10** [comment]
Okay, so the pipelines are independent. Doing this:
```
Broadcaster<Object> f = Broadcaster.create();
Fluxion<Object> b2 = f.map(t-> new Object());

b2.consume(System.err::println);
b2.consume(System.err::println);
b2.consume(System.err::println);
f.onNext(new Object());
```
Results in 
```
java.lang.Object@3b81a1bc
java.lang.Object@64616ca2
java.lang.Object@13fee20c
```

These are definitely different objects, so I can assume this was the intended behavior.

**Comment by smaldini** [comment]
Hey @masterav10 we have not changed project name , reactor-stream (apart from between friday night and saturday morning :D). It's still reactor-stream, with Fluxion and JDK8 tho :)

**Comment by masterav10** [comment]
For others interested, the answer to what I was trying to do was `cache()`. That ensures multiple downstream listeners see the same data.

You sure the name didn't change? Gradle downloaded the reactor-fluxion happily.
